### ISSUE TITLE
App logo icon is invisible on dark backgrounds

### ISSUE THREAD

**Issue by nekohayo** [aichingm/lonewolf#11]
This is how it looks like on a dark dock:

[Screencast from 2024-04-06 21-15-55.webm](https://github.com/aichingm/lonewolf/assets/479401/b9c1f83b-50ee-4560-bc27-9b94c594e32a)

My suggestion would be to fill the interior of the wolf with a solid color (white? light gray?) so that you can actually see the black lines.

**Comment by aichingm** [comment]
Sorry for the late response, currently working on a different project. 

As I see it there are two options:

* add a background below the "mesh"
* add a background "around" the icon like a circle or something.

**Comment by nekohayo** [comment]
I would recommend the former rather than the latter. Distinctively shaped icons are good for usability, whereas "everything is a circle / square" is detrimental to usability.
