### ISSUE TITLE
add a WIP-limit for columns: changing colours of counters, locking a column 

### ISSUE THREAD

**Issue by ofossum** [aichingm/lonewolf#14]
I'd like to suggest adding a WIP-limit for columns, as this is one of _the_ major aspects of kanban as a method.
(see [the Wikipedia article for Kanban](https://en.wikipedia.org/wiki/Kanban))

# User-Story

**As** a user
**I'd like** to visualize and set a limit of tasks in a given work-step (column)
**to** achieve better throughput and prevent work-items to pile up in my defined working-steps.

# Acceptance-criteria

**given** i open the main window
**when** i look at a column
**then** there is a counter of tasks in that column
**and** i can influence the behaviour of that shown counter

**given** i open the options menu of a column
**when** i open the option by clicking "edit"
**then** i have an option to set a limit of cards in this column
**and** i can define wether the counter should change colors
**and** i can define wether the column is locked and prevents adding further cards onto it

**Comment by aichingm** [comment]
I have this already in the backlog 
![image](https://github.com/aichingm/lonewolf/assets/6470959/9ecbbf49-1c24-4836-9e3c-0879c8f48e22)


@ofossum Would you feel comfortable to take a stab at implementing it in a PR? **PRs are always welcome!**

**Comment by ofossum** [comment]
Although i work in tech i'm not a programmer myself and have literally no experiences with typescript, vue.js or other languages present in this project. :/

**Comment by aichingm** [comment]
> Although i work in tech i'm not a programmer myself and have literally no experiences with typescript, vue.js or other languages present in this project. :/

No problem I will see that I find time to implement it.

**Comment by aichingm** [comment]
Implemented in e356903c50a3e55670d6d06049ad69f3c255da14 published in 1.4.0
