### ISSUE TITLE
[FR] Auto-save board

### ISSUE THREAD

**Issue by jay7x** [aichingm/lonewolf#15]
It'd be nice to have the auto-save feature, so no need to press Ctrl+S after every change :)

**Comment by aichingm** [comment]
I think it might be a good idea to add a option in the project settings to enable auto save :+1:

Would you feel comfortable writing a PR for this feature?

**Comment by aichingm** [comment]
Implemented in b3dac65ef1e42a7e4db13d43afa5a339c2cb755a published in 1.4.0
