### ISSUE TITLE
Addition of a Ctrl-S shortcut

### ISSUE THREAD

**Issue by Sh3mm** [aichingm/lonewolf#3]
I really like the app, however, adding shortcuts such as quick save would be nice as it currently necessary to open the side panel for each save

I would a an enhancement label, but I don't have the access to do it

**Comment by felix91gr** [comment]
This would be really awesome to have. I wanted to make such an issue as well :slightly_smiling_face:

**Comment by aichingm** [comment]
Hi guys! Over the last week I added this feature. There is also a section in the settings where shortcuts can be configured. 
You can test it by installing the test build: 

```
flatpak install https://dl.flathub.org/build-repo/58040/site.someones.Lonewolf.flatpakref
```

Please let me know how you like it and if there is something missing/not working etc. 😃
