### ISSUE TITLE
An icon (`32x32.png`) seems to be missing for the tauri context

### ISSUE THREAD

**Issue by felix91gr** [aichingm/lonewolf#5]
Okay so this is what I see:

![image](https://github.com/aichingm/lonewolf/assets/11747623/17eac6cd-c908-4870-9213-19167171f889)

I'm not sure how to fix it. The `Makefile` mentions no image under that name: `32x32.png`. 

But if we go look at `lonewolf-tauri/src-tauri/tauri.conf.json`, at lines 53-57 we do seem to find the cause:

https://github.com/aichingm/lonewolf/blob/afff8b5254628e45822bbe46793cb3788f0ed574/lonewolf-tauri/src-tauri/tauri.conf.json#L53-L57

Indeed, if I delete line 53, the error changes:

![image](https://github.com/aichingm/lonewolf/assets/11747623/ffdf6a15-2fcc-4045-a9b6-7acaa73c995b)

I think this error makes sense, since if we look at `lonewolf-tauri/src-tauri/icons`, we find only `512x512-lonewolf.png`.

If I delete the lines 53-57 and replace them by just `"icons/512x512-lonewolf.png"`, the result I get is this:

![image](https://github.com/aichingm/lonewolf/assets/11747623/d60780ed-f099-4e97-abbf-bbc5b653df90)

I'm still not certain the `.deb` binary I made is correct, but the change does seem to appease the build script.

**Comment by aichingm** [comment]
All those icons should be created with `make icons-tauri`. The tauri command `npm run tauri icon` creates them. 

https://github.com/aichingm/lonewolf/blob/afff8b5254628e45822bbe46793cb3788f0ed574/Makefile#L207-L207

**Comment by felix91gr** [comment]
Ah, I see. Indeed, that's what was missing. Thank you :)
