### ISSUE TITLE
Board title wraps in a broken way

### ISSUE THREAD

**Issue by nekohayo** [aichingm/lonewolf#8]
...when there's plenty of available space, and you use a long title such as "Must-do this month mission-critical stuff (not wishlist)", you get this:

![image](https://github.com/aichingm/lonewolf/assets/479401/5ff29623-8a7e-4867-8863-7518074349dd)

**Comment by aichingm** [comment]
Hey, thanks for letting me know! That should not happen. I will keep you updated when I have had time to work on this.

**Comment by aichingm** [comment]
fixed in 4f29764c6370c76510dc0bc83f4044ab84d04210, released on flathub in version 1.2.0
