### ISSUE TITLE
Autosave periodically, or show a save button and prompt about autosave on quit

### ISSUE THREAD

**Issue by nekohayo** [aichingm/lonewolf#9]
Currently, as soon as you do changes, it shows a warning icon in the board's header, saying "This board has unsaved changes!"

This info is not particularly helpful to the user (it does not provide any actionable thing), and it's also giving them "[sh!t work](https://zachholman.com/posts/shit-work/)".

Ideally it should just autosave every few minutes (to avoid the situation where an app crash or power loss or OS crash loses the changes). Alternatively, instead of showing that warning icon, it could show a "Save changes" button, with at tooltip that explains that changes are saved automatically on quit anyway... though if you're going to give users control over saving, then shouldn't you prompt them on quit to ask whether they want to save or discard the changes?

**Comment by aichingm** [comment]
> Ideally it should just autosave every few minutes

A copy of your work should be saved to a autosave-location after every change you make (when ever the yellow icon appears). There are issues with this solution, eg. when two sessions of the programm are running at the same time. I thinking of changing this to a less implicit to a more explicit action. 
You can try this out by not saving before closing and then reopening Lonewolf, unsaved changes should still be there!

I like the idea of changing the icon to a button, I will think about the close and autosave ideas. I will keep you posted if I make any progress on this.

**Comment by aichingm** [comment]
Added additional feature "auto save" via #15
